import { useState } from 'react'
import { Section } from '../ui/Section'
import { Card } from '../ui/Card'
import { Link } from '../ui/Link'
import { getSiteCopy, type Locale } from '../../content/localization'

export function CreatorSection({ locale = 'es' }: { locale?: Locale }) {
  const [imageError, setImageError] = useState(false)
  const copy = getSiteCopy(locale).creator
  return <Section id="creador" className="py-16 sm:py-20 md:py-24"><Card className="relative overflow-hidden p-5 sm:p-7 md:p-8"><div className="absolute inset-0 -z-10 bg-gradient-to-br from-[rgb(var(--p-accent-rgb)/0.12)] via-transparent to-[rgb(var(--p-accent2-rgb)/0.1)]" /><div className="grid gap-6 sm:gap-7 md:grid-cols-[0.88fr_1.12fr] md:items-center"><div className="flex items-center justify-center md:justify-start"><div className="relative"><div className="absolute -inset-2.5 rounded-[28px] bg-[rgb(var(--p-accent-rgb)/0.2)] blur-2xl sm:-inset-3 sm:rounded-[36px]" aria-hidden /><div className="relative h-48 w-48 overflow-hidden rounded-[24px] border border-[rgb(var(--p-accent-rgb)/0.35)] shadow-[0_18px_40px_-28px_rgba(124,58,237,0.6)] sm:h-60 sm:w-60 sm:rounded-[32px] md:h-72 md:w-72">{!imageError ? <img src="/IMG/foto.jpeg" alt={copy.imageAlt} loading="lazy" onError={() => setImageError(true)} className="h-full w-full object-cover" /> : <div className="flex h-full w-full items-center justify-center bg-[rgb(var(--p-accent-rgb)/0.18)]"><span className="text-2xl font-semibold text-white">AD</span></div>}</div></div></div><div><h3 className="font-display text-[1.65rem] font-semibold text-white sm:text-2xl md:text-4xl">{copy.title}</h3><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-300 md:text-base">{copy.p1}</p><p className="p-text-muted mt-4 max-w-2xl text-sm leading-relaxed md:text-base">{copy.p2}</p><p className="p-text-muted mt-3 max-w-2xl text-sm leading-relaxed md:text-base">{copy.p3}</p><p className="mt-4 max-w-2xl text-sm text-slate-400">{copy.impulse} <span className="text-slate-300">Agustin Delgado</span></p><div className="mt-6 flex flex-wrap gap-3"><Link href="https://www.linkedin.com/in/agustin-delgado-data98615190/" target="_blank" rel="noopener noreferrer" className="p-btn-primary rounded-[var(--radius-pill)] px-5 py-2 text-sm font-semibold">{copy.linkedin}</Link><Link href="https://github.com/Agus-Delgado" target="_blank" rel="noopener noreferrer" className="p-btn-secondary rounded-[var(--radius-pill)] px-5 py-2 text-sm font-semibold">{copy.github}</Link></div></div></div></Card></Section>
}
